### ISSUE TITLE
bandl installation failed in python39

### ISSUE THREAD

**Issue by sudheer628** [stockalgo/bandl#49]
PS C:\Users\sai-s\Documents> pip install bandl --user
Collecting bandl
  Using cached bandl-0.1.0-py3-none-any.whl (25 kB)
Requirement already satisfied: openpyxl in c:\users\sai-s\appdata\roaming\python\python39\site-packages (from bandl) (3.0.10)
Requirement already satisfied: lxml in c:\users\sai-s\appdata\roaming\python\python39\site-packages (from bandl) (4.9.1)
Collecting datetime
  Using cached DateTime-4.5-py2.py3-none-any.whl (52 kB)
Requirement already satisfied: requests in c:\users\sai-s\appdata\local\programs\python\python39\lib\site-packages (from bandl) (2.28.1)
Requirement already satisfied: pandas in c:\users\sai-s\appdata\roaming\python\python39\site-packages (from bandl) (1.4.3)
Requirement already satisfied: beautifulsoup4 in c:\users\sai-s\appdata\roaming\python\python39\site-packages (from bandl) (4.11.1)
Collecting futures
  Using cached futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\sai-s\AppData\Roaming\Python\Python39\site-packages\setuptools\__init__.py", line 247, in <module>
          monkey.patch_all()
        File "C:\Users\sai-s\AppData\Roaming\Python\Python39\site-packages\setuptools\monkey.py", line 99, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:\Users\sai-s\AppData\Roaming\Python\Python39\site-packages\setuptools\monkey.py", line 159, in patch_for_msvc_specialized_compiler
          patch_func(*msvc14('_get_vc_env'))
        File "C:\Users\sai-s\AppData\Roaming\Python\Python39\site-packages\setuptools\monkey.py", line 149, in patch_params
          mod = import_module(mod_name)
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "C:\Users\sai-s\AppData\Roaming\Python\Python39\site-packages\setuptools\_distutils\_msvccompiler.py", line 20, in <module>
          import unittest.mock as mock
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\unittest\mock.py", line 26, in <module>
          import asyncio
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\asyncio\__init__.py", line 8, in <module>
          from .base_events import *
        File "C:\Users\sai-s\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 18, in <module>
          import concurrent.futures
        File "C:\Users\sai-s\AppData\Local\Temp\pip-install-2vk14co1\futures_5710be2a01934fc18ba958bfb2b9512f\concurrent\futures\__init__.py", line 8, in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "C:\Users\sai-s\AppData\Local\Temp\pip-install-2vk14co1\futures_5710be2a01934fc18ba958bfb2b9512f\concurrent\futures\_base.py", line 357
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details

**Comment by surakesh** [comment]
Anyone know how to solve this issue of installation?

**Comment by coshec** [comment]
faced same issue with pip 24.0 on Windows
